name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.5.0 --activate

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          yarn install

      - name: Build assets
        run: yarn build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo lsof -t -i:3000 | xargs sudo kill -9
            cd /home/ubuntu/print_lab
            git pull origin main
            bundle install
            yarn install
            yarn build
            bundle exec rails db:migrate:with_data RAILS_ENV=production
            RAILS_ENV=production bundle exec puma -C config/puma.rb
